[package]
name = "teste"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.27.2"
chrono = "0.4.37"
libc = "0.2"
nfd = "0.0.4"

 